name: Preview Generation on Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          json: true
          write_output_files: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
        python-version: '3.x'
      - name: Install CI dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
      - name: Generate Preview Page
        id: generate
        run: |
          python scripts/generate_preview.py ${{ secrets.deploy_api_key }}
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ steps.generate.outputs.deploy_links }}